apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-s3-video-deployment
  labels:
    app: upload-s3-video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-s3-video
  template:
    metadata:
      labels:
        app: upload-s3-video
    spec:
      serviceAccountName: my-app-sa
      containers:
        - name: upload-s3-video
          image: IMAGE_CORE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_SESSION_TOKEN
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SESSION_TOKEN
            - name: BUCKET_NAME
              value: "soat7-videos-fiap"
            - name: NAMESPACE
              value: "hackaton-soat7-2025"
            - name: PROCESS_VIDEO
              value: "process-video"
            - name: PROCESS_VIDEO_IMAGE
              value: "737021845667.dkr.ecr.us-east-1.amazonaws.com/process-image:1.0.0"
            - name: REDIS_MID_URL
              value: "http://redis-communication-service"
            - name: REGION
              value: "us-east-1"
            - name: SHARED_DISK
              value: "/opt/app/shared"
            - name: UPLOAD_IMAGE
              value: "upload-image"
            - name: UPLOAD_IMAGE_IMAGE
              value: "737021845667.dkr.ecr.us-east-1.amazonaws.com/upload-s3:1.0.0"
            - name: UPLOAD_VIDEO
              value: "upload-video"
            - name: UPLOAD_VIDEO_IMAGE
              value: "737021845667.dkr.ecr.us-east-1.amazonaws.com/upload-s3:1.0.0"
            - name: MAX_EXECUTION_PER_POD
              value: "2"
            - name: STEP
              value: "VIDEO"
          volumeMounts:
            - name: app-storage
              mountPath: "/opt/app/shared"
      volumes:
        - name: app-storage
          persistentVolumeClaim:
            claimName: app-pvc